---
title: "Gov 50 Final Project"
author: "Eric Thompson"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to veterans in politics, specifically looking at if veterans are more likely to win political races or if veterans are more likely to vote for veteran candidates.


Are military veterans who run for political office more likely to win than non-veterans? Also, are veterans more likely to vote for fellow military veterans running for office than non-veterans? In this study, I plan to analyze voting results of military veterans and non-veteran candidates, as well as voting by US military veterans and non-veterans, to determine if veterans that run for political office are more likely to win than non-veterans. I hypothesize that veterans are more likely to win office than non-veterans, and that veterans are more likely to vote for fellow veterans than non-veteran candidates, and more so than non-veteran voters. I expect that there are more underlying factors that make this so, such as picking and choosing where and when to run by veteran candidates where they have the best chance to lure a particular set of voters, etc, but it would first be interesting to see if these hypotheses can be supported or not. My data is a CCES 2022 survey result, that includes a person's history with the military (i.e. currently serving, used to serve, never served), their political leanings, the candidates on which they voted for each election (House, Senate, President, Governor), and who the other candidate(s) were in those elections. The explanatory variables of interest would be whether a candidate is a veteran or not (determined by a value of 1 or 0 once the names are mutated to a variable that assigns a value based off the name) and whether or not a person is a veteran (for the second question). Currently the veteran is split up into 5 categories, but it will be changed to only be a 1 or 0 value, indicating if you have ever served in the military or not. The outcome variable would be the proportion of veterans that won their elections vs. the proportion of non-veterans who did, and for the question whether veterans are more likely to vote for fellow veterans the outcome will be the percentage of the time that veterans voted for veteran candidates vs. the time they voted for non-veteran candidates. It would also be interesting to see how often veterans vote outside of party lines for veteran candidates. If we see that veteran candidates win their elections more often in the dataset than non-veterans, this would provide support for my hypothesis. If we see that veterans vote more often for veteran candidates than non-veterans, this would also be supportive of my second hypothesis. A pattern that would disprove my hypothesis would be if we see that non-veteran candidates won elections a greater proportion of the time than veteran candidates, or that veterans were no more likely to vote for military veterans that were running for office than they were to vote for non-veterans. 





